In [1]:
import pandas as pd
import numpy as np

In [2]:
entities = pd.read_csv('C:\\Users\\emanf\\OneDrive\\Desktop\\anime recomendation system\\datasets\\raw\\entities.csv')

In [3]:
entities.head()

   entity_id entity_type                   name image_url
0          1      studio  Bandai Namco Pictures       NaN
1          2    producer               TV Tokyo       NaN
2          3    producer                Aniplex       NaN
3          4    producer                 Dentsu       NaN
4          5    licensor             Funimation       NaN

In [4]:
anime = pd.read_csv('C:\\Users\\emanf\\OneDrive\\Desktop\\anime recomendation system\\datasets\\raw\\anime.csv')

In [5]:
anime.head()

,anime_id,title,score,rank,popularity,members,synopsis,start_date,end_date,type,episodes,image_url
0,28977,Gintama°,9.05,8,347,680037,"Gintoki, Shinpachi, and Kagura return as the f...",2015-01-01,2016-01-01,TV,51.0,https://cdn.myanimelist.net/images/anime/3/720...
1,57555,Chainsaw Man Movie: Reze-hen,9.18,2,962,282129,Sequel to Chainsaw Man .,2025-01-01,2025-01-01,Movie,1.0,https://cdn.myanimelist.net/images/anime/1763/...
2,11061,Hunter x Hunter (2011),9.03,9,8,3107455,Hunters devote themselves to accomplishing haz...,2011-01-01,2014-01-01,TV,148.0,https://cdn.myanimelist.net/images/anime/1337/...
3,52991,Sousou no Frieren,9.29,1,121,1269074,During their decade-long quest to defeat the D...,2023-01-01,2024-01-01,TV,28.0,https://cdn.myanimelist.net/images/anime/1015/...
4,9969,Gintama',9.02,11,406,601940,"After a one-year hiatus, Shinpachi Shimura ret...",2011-01-01,2012-01-01,TV,51.0,https://cdn.myanimelist.net/images/anime/4/503...

In [6]:
anime_characters = pd.read_csv('C:\\Users\\emanf\\OneDrive\\Desktop\\anime recomendation system\\datasets\\raw\\anime_characters.csv')

In [7]:
anime_characters.head()

   anime_id  character_id     role
0     28977             7     Main
1     28977             9  Unknown
2     28977            10     Main
3     28977             9  Unknown
4     28977            12     Main

In [8]:
anime_companies = pd.read_csv('C:\\Users\\emanf\\OneDrive\\Desktop\\anime recomendation system\\datasets\\raw\\anime_companies.csv')

In [9]:
anime_companies.head()

   anime_id  company_id      role
0     28977           1    Studio
1     28977           2  Producer
2     28977           3  Producer
3     28977           4  Producer
4     28977           5  Licensor

In [10]:
anime_genres = pd.read_csv('C:\\Users\\emanf\\OneDrive\\Desktop\\anime recomendation system\\datasets\\raw\\anime_genres.csv')

In [11]:
anime_genres.head()

   anime_id                         genre
0     28977                 Action Action
1     28977                 Comedy Comedy
2     28977                 Sci-Fi Sci-Fi
3     28977    Theme::Gag Humor Gag Humor
4     28977  Theme::Historical Historical

In [12]:
merged_df = anime.copy()

dfs_to_merge = [
    anime_characters,
    anime_companies,
    anime_genres,
    
]

for df in dfs_to_merge:
    merged_df = merged_df.merge(
        df,
        on="anime_id",
        how="inner"
    )

merged_df.to_csv("merged.csv", index=False)

In [13]:
merge = pd.read_csv('merged.csv')

In [30]:
merge.head(1)

,anime_id,title,score,rank,popularity,members,synopsis,start_date,end_date,type,episodes,image_url,character_id,role_x,company_id,role_y,genre
0,28977,Gintama°,9.05,8,347,680037,"Gintoki, Shinpachi, and Kagura return as the f...",2015-01-01,2016-01-01,TV,51.0,https://cdn.myanimelist.net/images/anime/3/720...,7,Main,1,Studio,Action Action

In [18]:
print(merge.shape)

(3035624, 17)

In [19]:
merge.info()

<class 'pandas.DataFrame'>
RangeIndex: 3035624 entries, 0 to 3035623
Data columns (total 17 columns):
 #   Column        Dtype
---  ------        -----
 0   anime_id      int64
 1   title         str
 2   score         float64
 3   rank          int64
 4   popularity    int64
 5   members       int64
 6   synopsis      str
 7   start_date    str
 8   end_date      str
 9   type          str
 10  episodes      float64
 11  image_url     str
 12  character_id  int64
 13  role_x        str
 14  company_id    int64
 15  role_y        str
 16  genre         str
dtypes: float64(2), int64(6), str(9)
memory usage: 393.7 MB

In [20]:
merge.duplicated().sum()

np.int64(1290948)

In [21]:
merge.drop_duplicates(inplace=True)

In [22]:
print(merge.shape)

(1744676, 17)

In [25]:
print(merge.isnull().sum())

anime_id            0
title               0
score               0
rank                0
popularity          0
members             0
synopsis          275
start_date         18
end_date        12428
type                0
episodes         6328
image_url           0
character_id        0
role_x              0
company_id          0
role_y              0
genre               0
dtype: int64

In [26]:
merge.duplicated().sum()

np.int64(0)

In [27]:
df = merge.dropna(subset=["synopsis"])

In [29]:
print(df.isnull().sum())

anime_id            0
title               0
score               0
rank                0
popularity          0
members             0
synopsis            0
start_date         18
end_date        12428
type                0
episodes         6328
image_url           0
character_id        0
role_x              0
company_id          0
role_y              0
genre               0
dtype: int64

In [44]:
data_frame = df[["anime_id", "title","score","rank", "synopsis","type", "image_url", "genre","start_date","end_date","episodes"]]

In [75]:
data_frame.head(15)

,anime_id,title,score,rank,synopsis,type,image_url,genre,start_date,end_date,episodes,tags
0,28977,Gintama°,9.05,8,"[Gintoki, Shinpachi, and Kagura return as the ...",TV,https://cdn.myanimelist.net/images/anime/3/720...,[Action],2015-01-01,2016-01-01,51.0,"Action Gintoki, Shinpachi, and Kagura return a..."
1,28977,Gintama°,9.05,8,"[Gintoki, Shinpachi, and Kagura return as the ...",TV,https://cdn.myanimelist.net/images/anime/3/720...,[Comedy],2015-01-01,2016-01-01,51.0,"Comedy Gintoki, Shinpachi, and Kagura return a..."
2,28977,Gintama°,9.05,8,"[Gintoki, Shinpachi, and Kagura return as the ...",TV,https://cdn.myanimelist.net/images/anime/3/720...,[Sci-Fi],2015-01-01,2016-01-01,51.0,"Sci-Fi Gintoki, Shinpachi, and Kagura return a..."
3,28977,Gintama°,9.05,8,"[Gintoki, Shinpachi, and Kagura return as the ...",TV,https://cdn.myanimelist.net/images/anime/3/720...,[Gag Humor],2015-01-01,2016-01-01,51.0,"Gag Humor Gintoki, Shinpachi, and Kagura retur..."
4,28977,Gintama°,9.05,8,"[Gintoki, Shinpachi, and Kagura return as the ...",TV,https://cdn.myanimelist.net/images/anime/3/720...,[Historical],2015-01-01,2016-01-01,51.0,"Historical Gintoki, Shinpachi, and Kagura retu..."
5,28977,Gintama°,9.05,8,"[Gintoki, Shinpachi, and Kagura return as the ...",TV,https://cdn.myanimelist.net/images/anime/3/720...,[Parody],2015-01-01,2016-01-01,51.0,"Parody Gintoki, Shinpachi, and Kagura return a..."
6,28977,Gintama°,9.05,8,"[Gintoki, Shinpachi, and Kagura return as the ...",TV,https://cdn.myanimelist.net/images/anime/3/720...,[Samurai],2015-01-01,2016-01-01,51.0,"Samurai Gintoki, Shinpachi, and Kagura return ..."
7,28977,Gintama°,9.05,8,"[Gintoki, Shinpachi, and Kagura return as the ...",TV,https://cdn.myanimelist.net/images/anime/3/720...,[Shounen],2015-01-01,2016-01-01,51.0,"Shounen Gintoki, Shinpachi, and Kagura return ..."
960,57555,Chainsaw Man Movie: Reze-hen,9.18,2,[Sequel to Chainsaw Man .],Movie,https://cdn.myanimelist.net/images/anime/1763/...,[Action],2025-01-01,2025-01-01,1.0,Action Sequel to Chainsaw Man .
961,57555,Chainsaw Man Movie: Reze-hen,9.18,2,[Sequel to Chainsaw Man .],Movie,https://cdn.myanimelist.net/images/anime/1763/...,[Fantasy],2025-01-01,2025-01-01,1.0,Fantasy Sequel to Chainsaw Man .
962,57555,Chainsaw Man Movie: Reze-hen,9.18,2,[Sequel to Chainsaw Man .],Movie,https://cdn.myanimelist.net/images/anime/1763/...,[Gore],2025-01-01,2025-01-01,1.0,Gore Sequel to Chainsaw Man .
963,57555,Chainsaw Man Movie: Reze-hen,9.18,2,[Sequel to Chainsaw Man .],Movie,https://cdn.myanimelist.net/images/anime/1763/...,[Urban Fantasy],2025-01-01,2025-01-01,1.0,Urban Fantasy Sequel to Chainsaw Man .
964,57555,Chainsaw Man Movie: Reze-hen,9.18,2,[Sequel to Chainsaw Man .],Movie,https://cdn.myanimelist.net/images/anime/1763/...,[Shounen],2025-01-01,2025-01-01,1.0,Shounen Sequel to Chainsaw Man .
1460,11061,Hunter x Hunter (2011),9.03,9,[Hunters devote themselves to accomplishing ha...,TV,https://cdn.myanimelist.net/images/anime/1337/...,[Action],2011-01-01,2014-01-01,148.0,Action Hunters devote themselves to accomplish...
1461,11061,Hunter x Hunter (2011),9.03,9,[Hunters devote themselves to accomplishing ha...,TV,https://cdn.myanimelist.net/images/anime/1337/...,[Adventure],2011-01-01,2014-01-01,148.0,Adventure Hunters devote themselves to accompl...

In [46]:
print(data_frame.isnull().sum())

anime_id          0
title             0
score             0
rank              0
synopsis          0
type              0
image_url         0
genre             0
start_date       18
end_date      12428
episodes       6328
dtype: int64

In [47]:
data_frame = data_frame.dropna(subset=["start_date", "end_date", "episodes"])

In [63]:
data_frame["genre"] = data_frame["genre"].apply(lambda x: [x] if pd.notna(x) else [])

In [48]:
print(data_frame.isnull().sum())

anime_id      0
title         0
score         0
rank          0
synopsis      0
type          0
image_url     0
genre         0
start_date    0
end_date      0
episodes      0
dtype: int64

In [51]:
data_frame.drop_duplicates(inplace=True)

In [53]:
data_frame.duplicated().sum()

np.int64(0)

In [61]:
import re

def clean_genre(text):
    if pd.isna(text):
        return text

    # Remove prefixes like Theme:: or Demographic::
    text = re.sub(r'^[A-Za-z]+::', '', text)

    # Remove duplicated text
    text = re.sub(r'^(.+?)\s+\1$', r'\1', text)

    return text.strip()

data_frame["genre"] = data_frame["genre"].apply(clean_genre)

In [67]:
data_frame["synopsis"] = data_frame["synopsis"].apply(
    lambda x: [x] if pd.notna(x) else []
)

In [71]:
data_frame["tags"] = data_frame["genre"] + data_frame["synopsis"]

In [74]:
data_frame["tags"] = data_frame["tags"].apply(lambda x: " ".join(x))

In [76]:
new_data_frame = data_frame[["anime_id", "title","score","rank","type", "image_url","start_date","end_date","episodes","tags"]]

In [77]:
new_data_frame.to_csv("processed_data.csv", index=False)